StudentManagerC/Models/StudentModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StudentManagerC.Models
{
    public class StudentModel
    {
        public string Name { set; get; }
        public string ID { set; get; }
        public string Age { set; get; }
    }
}

StudentManagerC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentManagerC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {

            //
            ViewBag.Message = "Your application description page.";
            ViewBag.todayNewInfo = "mvc template";



            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

StudentManagerC/Controllers/NotifycationController.cs
using StudentManagerC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentManagerC.Controllers
{
    public class NotifycationController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ShowListStudent()
        {
            return View("ShowListTeachers");
        }


        [HttpPost]
        public ActionResult Save(StudentModel model)
        {
            ViewBag.IsSaved = true;
            return View("Index", model);
        }
    }
}

StudentManagerC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About - meeting on 8th";
    var today = "meeting for the 5th part";
}
<h1>@today</h1>
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<input type="button" class="btn btn-danger" value="View Data"/>
<input  type="button" value="Create New" />
<p>Use this area to provide additional information.</p>

StudentManagerC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

StudentManagerC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

StudentManagerC/Views/Notifycation/Index.cshtml
@model StudentManagerC.Models.StudentModel
@{
    ViewBag.Title = "Index";
}

<h2> Nothing</h2>
<div class="container">
    <div class="row col-md-12">
        <div class="col-md-6">
            @using (Html.BeginForm("Save", "Notifycation", FormMethod.Post))
            {
                <div>
                    <div class="form-group">
                        <label>Student's id</label>
                        <input name="ID" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label>Student's name</label>
                        <input name="Name" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label>Student's age</label>
                        <input name="Age" class="form-control" />
                    </div>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            }
        </div>
        <div class="col-md-6">
            @if (ViewBag.IsSaved != null && (bool)ViewBag.IsSaved)
            {
                <div>
                    <form class="form-horizontal">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Id: </label>
                            <div class="col-sm-10">
                                @Model.ID
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Name: </label>
                            <div class="col-sm-10">
                                @Model.Name
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Age: </label>
                            <div class="col-sm-10">
                                @Model.Age
                            </div>
                        </div>
                    </form>
                </div>
            }
        </div>
    </div>
</div>

StudentManagerC/Views/Notifycation/ShowListStudent.cshtml
@{
    ViewBag.Title = "ShowListStudent";
}

<h2>ShowListStudent</h2>

StudentManagerC/Views/Notifycation/ShowListTeachers.cshtml
@{
    ViewBag.Title = "ShowList Teachers";
}

<h2>ShowList Teachers</h2>

StudentManagerC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Vào Notifycation", "Index", "Notifycation")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundlesOption/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>